main.go, pkg/aws/client.go
=> client can describe EC2 instances

deploy/Dockerfile, deploy/deployment.yaml
added dockerfile and deployment.yaml
=> added dockerfile and deployment.yaml

main.go
Client can read secret in a namespace and describe EC2/S3 instances
=> read secret and describe EC2/S3 resources

main.go, pkg/awsManager/ec2Manager.go
Service can delete EC2 instance. 
Not the final commit, needs testing
=> Service can delete EC2 instances

deploy/Dockerfile
this change was made in order to integrate it with openshft/release CI
=> Migrating docker image from single stage to multi stage

Makefile, hack/app_sre_build_deploy.sh
adding config files to make it compatible with the app-sre pipeline
=> v3 Cluster deployment configuration

README.md
=> Adds how-to to readme

main.go, pkg/aws/client.go, pkg/awsManager/aws_manager_test.go, pkg/awsManager/ec2Manager.go, pkg/awsManager/s3Manager.go, pkg/awsManager/vpcVpnManager.go, pkg/mock/client_generated.go
service can delete VPC and VPN
=> Osd 4283 service can delete VPC and VPN

deploy/deployment.yaml, deploy/template.yaml
adding template for app-sre pipeline
=> osd 4489 app sre pipeline

deploy/aws-account-operator-template.yaml, deploy/aws-account-shredder-template.yaml
=> added all the resource in the template.yaml

deploy/aws-account-shredder-template.yaml
updated role permission from '*' to individual permission
=> updated permissions for app-sre pipeline

deploy/aws-account-shredder-template.yaml
changed imagepullpolicy to 'always'
=> changed image pull policy in template

deploy/aws-account-shredder-template.yaml
fixed parameter for app-sre pipeline.....
=> Changes with respect to comments from app-sre team

main.go, pkg/awsManager/ec2Manager.go, pkg/awsManager/s3Manager.go, pkg/awsv1alpha1/accounts.go
=> Adding log messages ( osd 4042 / osd 4043 / osd-4190 )

debug/README.md, debug/security_group_blocked_resources.sh, debug/vpc_blocked_resources.sh
added some debug script with readme.md
=> added some debug script with readme

main.go, pkg/aws/client.go, pkg/awsManager/aws_manager_test.go, pkg/awsManager/ebsManager.go, pkg/mock/client_generated.go
=> Osd 4490 Service can delete EBS 

main.go, pkg/aws/client.go, pkg/awsManager/aws_manager_test.go, pkg/awsManager/efsManager.go, pkg/mock/client_generated.go
=> Osd 4401Service can delete EFS resources

debug/README.md
=> updated README.md

pkg/awsManager/ebsManager.go, pkg/awsManager/s3Manager.go, pkg/awsManager/vpcVpnManager.go
Removed all the fmt.println () statements.
=> removed debug messages

go.mod, main.go, pkg/awsManager/ebsManager.go, pkg/awsManager/ec2Manager.go, pkg/awsManager/efsManager.go, pkg/awsManager/route53_manager.go, pkg/awsManager/s3Manager.go, pkg/awsManager/vpcVpnManager.go
Improve error handling and logging, covering resources that fail to be deleted.
Card -> https://issues.redhat.com/browse/OSD-4827
=> improve error handling and logging

deploy/deployment.yaml, main.go, pkg/aws/client.go, pkg/awsManager/ebsManager.go, pkg/awsManager/ec2Manager.go, pkg/awsManager/efsManager.go, pkg/awsManager/route53_manager.go, pkg/awsManager/s3Manager.go, pkg/awsManager/vpcVpnManager.go, pkg/localMetrics/localMetrics.go
Adds some metrics to satisfy [OSD-4830](https://issues.redhat.com/browse/OSD-4830).
=> Add metrics

deploy/aws-account-operator-template.yaml
Ref [OSD-7582](https://issues.redhat.com/browse/OSD-7582):
Reverting previous changes
slack thread for spammy errors: https://coreos.slack.com/archives/C0140EM7BFW/p1631624920061700
=> [OSD-7582] Reverts access to accounts/status

.gitignore, README.md
Updated docs to reduce speedbumps for local testing
=> Update docs for local testing

Makefile, README.md, main.go, pkg/awsManager/aws_manager_test.go, pkg/awsManager/efsManager.go, workflow/get_logs.sh, workflow/kill_pod.sh
Ref: https://issues.redhat.com/browse/OSD-5616
=> [OSD-5616] Reintroduce EFS cleanup to Shredder

.golangci.yml, Makefile
This PR adds linter validation and unit testing to makefile https://issues.redhat.com/browse/OSD-8597
=> add linters

main.go, pkg/awsManager/aws_manager_test.go, pkg/awsManager/ebsManager.go, pkg/awsManager/eipManager.go, pkg/awsManager/route53_manager.go, pkg/awsManager/s3Manager.go
This PR fixes some misspellings and addresses some warnings from the linters https://issues.redhat.com/browse/OSD-9033
=> fix mispell and refactor

OWNERS
Update owners file which was quite out of date
=> Update Owners File

main.go, pkg/awsManager/s3Manager.go
* updating supported region list 
* adding a note about s3 bucket inefficiency
=> updating supported region list to match AAO

Makefile, README.md, hack/shred_accounts.sh, main.go
* Improved documentation around ad-hoc shredding
* added bash script to ad-hoc shred multiple accounts at once
=> adding bulk ad-hock shredding support

OWNERS
Remove macgregor from owners as part of his leaver process.
cc @macgregor
=> remove owner macgregor

README.md
Per https://issues.redhat.com/browse/OSD-22360
=> Bumping repo for image rebuild with the latest version of ubi
